{
	"document_title": "CVE-2023-49080",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2023-49080"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2023-12-06T00:09:00Z",
				"description": "current"
			}
		},
		"initial_release_date": "2023-12-06T00:09:00Z",
		"current_release_date": "2023-12-06T00:09:00Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2023-49080",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "The Jupyter Server provides the backend (i.e. the core services, APIs, and REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab, and Voila. Unhandled errors in API requests coming from an authenticated user include traceback information, which can include path information. There is no known mechanism by which to trigger these errors without authentication, so the paths revealed are not considered particularly sensitive, given that the requesting user has arbitrary execution permissions already in the same environment. A fix has been introduced in commit `0056c3aa52` which no longer includes traceback information in JSON error responses. For compatibility, the traceback field is present, but always empty. This commit has been included in version 2.11.2. Users are advised to upgrade. There are no known workarounds for this vulnerability.",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python310-jupyter-server-2.11.2-1.1",
				"full_product_name": {
					"text": "python310-jupyter-server-2.11.2-1.1",
					"product_id": "python310-jupyter-server-2.11.2-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python310-jupyter-server-test-2.11.2-1.1",
				"full_product_name": {
					"text": "python310-jupyter-server-test-2.11.2-1.1",
					"product_id": "python310-jupyter-server-test-2.11.2-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-jupyter-server-2.11.2-1.1",
				"full_product_name": {
					"text": "python311-jupyter-server-2.11.2-1.1",
					"product_id": "python311-jupyter-server-2.11.2-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-jupyter-server-test-2.11.2-1.1",
				"full_product_name": {
					"text": "python311-jupyter-server-test-2.11.2-1.1",
					"product_id": "python311-jupyter-server-test-2.11.2-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python39-jupyter-server-2.11.2-1.1",
				"full_product_name": {
					"text": "python39-jupyter-server-2.11.2-1.1",
					"product_id": "python39-jupyter-server-2.11.2-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python39-jupyter-server-test-2.11.2-1.1",
				"full_product_name": {
					"text": "python39-jupyter-server-test-2.11.2-1.1",
					"product_id": "python39-jupyter-server-test-2.11.2-1.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python310-jupyter-server-2.11.2-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python310-jupyter-server-test-2.11.2-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-jupyter-server-2.11.2-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-jupyter-server-test-2.11.2-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python39-jupyter-server-2.11.2-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python39-jupyter-server-test-2.11.2-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "The Jupyter Server provides the backend (i.e. the core services, APIs, and REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab, and Voila. Unhandled errors in API requests coming from an authenticated user include traceback information, which can include path information. There is no known mechanism by which to trigger these errors without authentication, so the paths revealed are not considered particularly sensitive, given that the requesting user has arbitrary execution permissions already in the same environment. A fix has been introduced in commit `0056c3aa52` which no longer includes traceback information in JSON error responses. For compatibility, the traceback field is present, but always empty. This commit has been included in version 2.11.2. Users are advised to upgrade. There are no known workarounds for this vulnerability.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2023-49080",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python310-jupyter-server-2.11.2-1.1",
						"openSUSE Tumbleweed:python310-jupyter-server-test-2.11.2-1.1",
						"openSUSE Tumbleweed:python311-jupyter-server-2.11.2-1.1",
						"openSUSE Tumbleweed:python311-jupyter-server-test-2.11.2-1.1",
						"openSUSE Tumbleweed:python39-jupyter-server-2.11.2-1.1",
						"openSUSE Tumbleweed:python39-jupyter-server-test-2.11.2-1.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "4.1",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:L/I:N/A:N"
				}
			}
		}
	]
}
