{
	"document_title": "CVE-2017-5992",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2017-5992"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "7",
				"date": "2023-12-08T01:35:08Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-05-30T13:53:20Z",
		"current_release_date": "2023-12-08T01:35:08Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2017-5992",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python36-openpyxl-3.0.7-1.2",
				"full_product_name": {
					"text": "python36-openpyxl-3.0.7-1.2",
					"product_id": "python36-openpyxl-3.0.7-1.2"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-openpyxl-3.0.7-1.2",
				"full_product_name": {
					"text": "python38-openpyxl-3.0.7-1.2",
					"product_id": "python38-openpyxl-3.0.7-1.2"
				}
			},
			{
				"type": "Product Version",
				"name": "python39-openpyxl-3.0.7-1.2",
				"full_product_name": {
					"text": "python39-openpyxl-3.0.7-1.2",
					"product_id": "python39-openpyxl-3.0.7-1.2"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python36-openpyxl-3.0.7-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-openpyxl-3.0.7-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python39-openpyxl-3.0.7-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2017-5992",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python36-openpyxl-3.0.7-1.2",
						"openSUSE Tumbleweed:python38-openpyxl-3.0.7-1.2",
						"openSUSE Tumbleweed:python39-openpyxl-3.0.7-1.2"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5.8",
					"vector_v_2": "AV:N/AC:M/Au:N/C:P/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "8.2",
					"vector_v_3": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:H"
				}
			}
		}
	]
}
