{
  "document_title": "CVE-2021-42343",
  "document_type": "SUSE CVE",
  "document_publisher": {
    "type": "Vendor",
    "contact_details": "security@suse.de",
    "issuing_authority": "SUSE Security Team"
  },
  "document_tracking": {
    "identification": {
      "id": "SUSE CVE-2021-42343"
    },
    "status": "Interim",
    "version": "1",
    "revision_history": {
      "revision": {
        "number": "4",
        "date": "2022-01-24T02:27:55Z",
        "description": "current"
      }
    },
    "initial_release_date": "2021-10-28T01:34:11Z",
    "current_release_date": "2022-01-24T02:27:55Z",
    "generator": {
      "engine": "cve-database/bin/generate-cvrf-cve.pl",
      "date": "2020-12-27T01:00:00Z"
    }
  },
  "document_notes": [
    {
      "text": "CVE-2021-42343",
      "title": "CVE",
      "type": "Summary"
    },
    {
      "text": "An issue was discovered in the Dask distributed package before 2021.10.0 for Python. Single machine Dask clusters started with dask.distributed.LocalCluster or dask.distributed.Client (which defaults to using LocalCluster) would mistakenly configure their respective Dask workers to listen on external interfaces (typically with a randomly selected high port) rather than only on localhost. A Dask cluster created using this method (when running on a machine that has an applicable port exposed) could be used by a sophisticated attacker to achieve remote code execution.",
      "title": "Mitre CVE Description",
      "type": "Description"
    },
    {
      "text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "title": "Terms of Use",
      "type": "Legal Disclaimer"
    }
  ],
  "document_references": [
    {
      "type": "Self",
      "url": "https://www.suse.com/support/security/rating/",
      "description": "SUSE Security Ratings"
    }
  ],
  "product_tree": {
    "branch": [
      {
        "type": "Product Family",
        "name": "openSUSE Tumbleweed",
        "branch": [
          {
            "type": "Product Name",
            "name": "openSUSE Tumbleweed",
            "full_product_name": {
              "text": "openSUSE Tumbleweed",
              "product_id": "openSUSE Tumbleweed",
              "cpe": "cpe:/o:opensuse:tumbleweed"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Version",
        "name": "python38-distributed-2022.1.0-1.1",
        "full_product_name": {
          "text": "python38-distributed-2022.1.0-1.1",
          "product_id": "python38-distributed-2022.1.0-1.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python39-distributed-2022.1.0-1.1",
        "full_product_name": {
          "text": "python39-distributed-2022.1.0-1.1",
          "product_id": "python39-distributed-2022.1.0-1.1"
        }
      }
    ],
    "relationship": [
      {
        "product_reference": "python38-distributed-2022.1.0-1.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      },
      {
        "product_reference": "python39-distributed-2022.1.0-1.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      }
    ]
  },
  "vulnerability": {
    "notes": [
      {
        "text": "An issue was discovered in the Dask distributed package before 2021.10.0 for Python. Single machine Dask clusters started with dask.distributed.LocalCluster or dask.distributed.Client (which defaults to using LocalCluster) would mistakenly configure their respective Dask workers to listen on external interfaces (typically with a randomly selected high port) rather than only on localhost. A Dask cluster created using this method (when running on a machine that has an applicable port exposed) could be used by a sophisticated attacker to achieve remote code execution.",
        "title": "Vulnerability Description",
        "type": "General"
      }
    ],
    "cve": "CVE-2021-42343",
    "product_statuses": [
      {
        "type": "Fixed",
        "product_id": [
          "openSUSE Tumbleweed:python38-distributed-2022.1.0-1.1",
          "openSUSE Tumbleweed:python39-distributed-2022.1.0-1.1"
        ]
      }
    ],
    "threats": [
      {
        "type": "Impact",
        "description": "moderate"
      }
    ],
    "cvss_score_sets": {
      "score_set_v_2": {
        "base_score_v_2": "6.8",
        "vector_v_2": "AV:N/AC:M/Au:N/C:P/I:P/A:P"
      },
      "score_set_v_3": {
        "base_score_v_3": "9.8",
        "vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
      }
    }
  }
}
